### ISSUE TITLE
Change out the FlashWrapper plugin for FlashMessagesBootstrap plugin

### ISSUE THREAD

**Issue by bpamiri** [neokoenig/cfwheels-cli#25]
The FlashWrapper plugin is failing in CFWheels 2.0. I've submitted a Pull Request to them that would fix the issue and make the plugin work in CFWheels 2.0 but I'm not sure if that project is still active since the last commit is dated 2011. Therefore I've created a new plugin that simply takes the output of FlashMessages and modifies it for Bootstrap Alerts. It is now on forge box. This issue is a placeholder for the changes to be made to cfwheels-cli to swap out the two plugins and change the settings file to remove the entries that are no longer needed.

**Comment by neokoenig** [comment]
Fixed in 68b8ce9b91beb1745067d2596a4bfbcda04f63ad
Nice that the fix was like, one line of code :)

**Comment by bpamiri** [comment]
Ya the fix is pretty simple since the new plugin is in ForgeBox. I was actually working on a more comprehensive fix. Removing the old plugin that is currently being shipped with the cli, removing the settings from the config dir, as well as making some changes to the layout.cfm file. I'll still complete those and send you a pull request to cleanup the install.
