### ISSUE TITLE
Update list of available Wheels version in NEW command

### ISSUE THREAD

**Issue by bpamiri** [neokoenig/cfwheels-cli#35]
---------- Forwarded message ---------
From: Tom King <Unknown>
Date: Sunday, January 30, 2022 at 1:04:07 PM UTC-8
Subject: Re: Wheels CLI module for Commandbox

One fairly easy change would be to make it look up latest wheels versions from forgebox, rather than them being hard coded etc...

**Comment by bpamiri** [comment]
Should the current list be reduced down to:

1) Latest Stable Release
2) Bleeding Edge (Current Master Branch)

**Comment by neokoenig** [comment]
Sounds sensible to me.

**Comment by bpamiri** [comment]
I've submitted a PR for this that does a overhaul on the current wizard.
